### ISSUE TITLE
Preferences Cleanup

### ISSUE THREAD

**Issue by JonnyCodewalker** [lainsce/quilter#103]
Move `Show the Save Button` from Editor to Interface, since it is an Interface alteration.

Also, but that is a highly personal thing and I am not sure if many would like it, add an interface option to disable showing the `File | Preview` buttons at the top. I am using F1 for that anyway, so I don't need them.

**Comment by lainsce** [comment]
:+1: Will move Show the Save Button from Editor to Interface.
:-1:  Add an interface option to disable showing the File | Preview buttons at the top.

I'm not going to enable the disabling of core UI because that would be alienating to users.
The save button is tied to auto-saving so it's ephemeral if it's there or not,
while the Edit | Preview is core UI that always should be present.

**Comment by JonnyCodewalker** [comment]
Makes sense. Second was was just a small suggestion I didn't see fit for an own ticket for a reason :D

**Comment by lainsce** [comment]
Fixed in master/1.4.3
