### ISSUE TITLE
Not able to build

### ISSUE THREAD

**Issue by jishnu7** [lainsce/quilter#246]
I am trying to build the latest version (1.8.2) and getting following error in ArchLinux.

I am able to build version 1.7.0 without any problem.

```
../src/Application.vala:189.43-189.63: error: Assignment: Cannot convert from `GLib.List<Gtk.Window>' to `GLib.List<weak Gtk.Window>?'
            unowned List<weak Gtk.Window> wins = get_windows ();
                                          ^^^^^^^^^^^^^^^^^^^^^
../src/Application.vala:190.20-190.23: error: The name `wins' does not exist in the context of `Quilter.Application.get_last_win'
            return wins.length () > 0 ? wins.last ().data as MainWindow : null;
                   ^^^^
../src/Application.vala:190.41-190.44: error: The name `wins' does not exist in the context of `Quilter.Application.get_last_win'
            return wins.length () > 0 ? wins.last ().data as MainWindow : null;
```

**Comment by lainsce** [comment]
_NOTICE: I'm now in the middle of Uni midterms and as such, I cannot help you with fixing bugs until April 7th._

**Comment by Tinlegs** [comment]
Well the very best of luck in your Mid-terms - I look forwards to you fixing this after April 7th.  I'm trying to build it on Antergos and having the same problems as the chap above.
I'm a writer and and I find Quilter to be a fabulous tool for this.  I've had to resort to FocusWriter (Boo Hiss :( ) until I can get back to Quilter.
I hope you can fix it soon.
Many thanks for such a fabulous application :)

**Comment by lainsce** [comment]
Since I'm a nice guy I fixed this

**Comment by Tinlegs** [comment]
Ha Ha Ha - You are obviously not only a nice guy, but a SUPERSTAR!!

As it happens, I used to program back in the 80's so whilst I'd never seen 'vala' before and object-oriented programming makes my head spin, I actually had already done exactly what you have done when I first saw the compilation errors - I removed that "weak" reference and voila fixed it myself LOL - It's comforting to see that you did the same thing and than I'm obviously not as daft as I thought I was LOL.

So I confess that I have been using it still, but thank you very much for the fix - And that's where the good news ends..... I hate to tell you that I have since seen several quite sever bugs in this version, and lost three hours work as a result. However, get your mid-terms out of the way and you can worry about Quilter at your leisure - I still totally love it as an application - I'm just not sure I can trust it with my writing at the moment. Maybe I'll learn OOP and have a go myself LOL ;)

Good luck and thank you once again :)
