### ISSUE TITLE
Resize width of sidebar?

### ISSUE THREAD

**Issue by skyblue002** [lainsce/quilter#287]
The sidebar takes up too much screen space, horizontally. This becomes a problem when working on several documents at a time and switching between them:
![Quilter Screenshot](https://user-images.githubusercontent.com/41849249/67897597-1ffca400-fb35-11e9-99f8-b0743d8a8882.png)

Is there any way to resize it, not simply hide it? Hiding it doesn't help when working on multiple documents at a time (e.g. chapters or sections of a book or tutorial). In that case, it would need to be open, it would just need to take up less screen space.

If this is not a feature, may I suggest it for the future?

**Comment by lainsce** [comment]
Using a theme that isn't the default elementary one disqualifies the issue from being fixed as I don not have time to babysit for every Linux GTK theme. Sorry.

**Comment by skyblue002** [comment]
This isn't about the GTK theme, it's about the sidebar. I tried it with every other GTK theme I have, and the problem persists -- it's still much bigger than it has to be and takes up a lot of screen space. If you don't want to address this issue, that's fine. I can use another app. But, this isn't a matter of cleaning up somebody else's mess. It's just a matter of taking a look at the fact that the sidebar can't be resized, which is a feature I'm not the first user to ask about. It's a reasonable feature to add. But, it's your app. If you don't want to add that feature, that's entirely up to you.

**Comment by lainsce** [comment]
What I mean is that it might just be how that theme or this other theme handles sidebars.
If the problem persists with the elementary theme, then it's a different story, and then I'm willing to help.
I just have a no-customization rule to abide by otherwise I would have other show me "Hey I have problems here!" and they're using a broken GTK theme.

**Comment by 4jNsY6fCVqZv** [comment]
I can understand the no-customization rule very well from a developer's perspective.
I use the default elementary Juno. I already noticed that with the sidebar. I don't know yet how the error can be reproduced. At the moment, it seems to me that there is more space at an arbitrary point in the sidebar for a Quilter. So much space that the text editor almost seems to disappear and becomes unusable while the sidebar is open. And since it's not possible to bring the sidebar back into shape or reset the window, this becomes a real issue. Maybe we can do some research together and solve the problem?

**Comment by lainsce** [comment]
I think I found what makes it become unnecessarily big. Try making a header like this:
`# Really long headers bug the app`

I think that's the problem.

**Comment by 4jNsY6fCVqZv** [comment]
If you then shorten the long header again, does the sidebar adapt for you again?
p.s. I just noticed that a really very long header is not displayed completely in the outline, can that be?

**Comment by lainsce** [comment]
Yeah that's it then. We found the culprit. I'm going to see how to make these fit the outline tab without making it expand.

**Comment by 4jNsY6fCVqZv** [comment]
Nice, thank you so much for working on this!

**Comment by lainsce** [comment]
Basically I'll control the width of chars that can appear in the outline tab to an acceptable value. Ezpz.

**Comment by 4jNsY6fCVqZv** [comment]
You mean control in the sense of a line break?

**Comment by lainsce** [comment]
In the sense of:
`# Really long headers...`

Instead of:
`# Really long headers bug the app`

**Comment by lainsce** [comment]
Fixed.
