### ISSUE TITLE
How to modify styles in editor and export

### ISSUE THREAD

**Issue by shtonchjo** [lainsce/quilter#328]
On Quilter v. 2.2.2, the button "A" on top shows a list "Use Sans-serif / Serif / Monospace" which has no effect in the editor.

Also, when exporting, "#" titles are changed to capital letters with a small spacing between lines such that the text is hardly readable.

==> how to customize the styles used in both the editor and the export-to-pdf tool ?

Thanks!

**Comment by lainsce** [comment]
Let's go by parts.

1. That A button is for the preview, you change the font used in the preview there; to change the editor's font see in Preferences.

2. I'm going to fix that, should be small so closing the issue.

**Comment by shtonchjo** [comment]
Sorry to bring it back, I like the appearance of Quilter, but I'd like to tweak it as concerns the styles (in the editor and when exporting to PDF) --> is there a way to edit some css file for instance?

**Comment by lainsce** [comment]
I worry about letting people use CSS of their own instead of follow a template, because it may generate bad results and then the user comes at me and says "Pls help I am stuck can't read anything!" when they themselves have dug their hole. Also Quilter isn't supposed to be more customizable, it's not the focus of the app.
