### ISSUE TITLE
File path in top bar always shows 'No Documents Open'

### ISSUE THREAD

**Issue by razmarques** [lainsce/quilter#353]
### Issue description
Independently of which file is open, the top bar's subtitle always shows the message 'No Documents Open'. I include a link to a video reproducing this issue.

### Quilter version
2.5.1

### Video description
[Link](https://www.dropbox.com/s/gdh8zk9aketp1dw/issue_shot.mp4?dl=0)

**Comment by lainsce** [comment]
I've dropped this functionality on 3.0 (Next) due to its unpredictability and buggy behaviour.

If you're annoyed by it, I suggest some Unsee Juice. :sweat_smile: 
![Screenshot from 2020-11-22 12 01 21](https://user-images.githubusercontent.com/4886639/99907243-7b5a8080-2cba-11eb-8eca-ce8fc0798219.png)

**Comment by razmarques** [comment]
Thanks for your answer.
It is not a matter of being annoyed really. Just trying to help with feedback on an app I care.

If it is a buggy feature, taking it out would be the best thing to do. Personally I wouldn't miss it  much ;)

**Comment by lainsce** [comment]
> Just trying to help with feedback on an app I care.

:heart:
