### ISSUE TITLE
Saving files is confusing, lacks UI button

### ISSUE THREAD

**Issue by lightonflux** [lainsce/quilter#366]
Using the newest version from flathub. 3.1.2 on Fedora 33.

## no save button in GUI
When creating a file, there is no obvious save button anywhere. ctrl+(shift+)s works, but this has to be known by the user.

## indicator if file is saved is broken
Additionally, new files can be created. With text under the name that the document is not saved. 
If you don't find the button and close  + reopen it, you new document is already there, but empty, without indicator text that file is unsaved. 

## completely empty documents remembered for some reason 
In most programs if you open an empty document and don't write in it, it is not saved. Quilter will remember a possibly endless amount of "New documents".

## Video

https://user-images.githubusercontent.com/1377943/105634675-920a8880-5e5f-11eb-813d-b8938e3695a6.mp4

**Comment by lightonflux** [comment]
## Video2

Turns out sometimes the "new document" files are saved‽ But when you open them, they overwrite you current document. And the sidebar does not reflect the opened file name or state at all. 


https://user-images.githubusercontent.com/1377943/105634857-5c19d400-5e60-11eb-81c1-f8bdf3efabec.mp4

**Comment by lainsce** [comment]
I'll go one step at a time:

> no save button in GUI

That's because Quilter autosaves your work by default, and you can disable this and continue using Ctrl+S (or in a new version I'm coding, a save buton will be shown.)

> indicator if file is saved is broken

This is fixed in a new version I'm coding.

> completely empty documents remembered for some reason

This is to combat losing your transient documents in case of an accidental close before you actually meant to be done with them.

> But when you open them, they overwrite you current document.

This is fixed in a newer version I'm coding.
