### ISSUE TITLE
Issue with automatic saves

### ISSUE THREAD

**Issue by Tomires** [lainsce/quilter#91]
I just managed to lose a couple documents due to quilter mismatching filenames of previously opened files. The contents of previously opened files have been overwritten by contents of the currently opened file.

Unfortunately I will have to uninstall the application before this critical bug gets fixed, which is a shame because I really like the design. :(

**Comment by lainsce** [comment]
Let me help you! What is the version you have installed? If it is 1.3.8, I’m going to try finding what’s happening and fix for the next release. :D

**Comment by Tomires** [comment]
Whoops, I was a little bit trigger happy and uninstalled the app (so my .md files open in a different editor).  It was the latest upstream release through AppCenter. 

I have been using the toolbar icon to open files, although I have noticed something weird about a week back when the titlebar failed to update after opening a new file (it showed the path to the previously opened file). 

I don't remember having more than two instances running at the same time, however I cannot vouch for that. What is the issue? Are different instances accessing shared resources containing information about opened files?

Thanks for a fast response!

**Comment by lainsce** [comment]
> What is the issue? Are different instances accessing shared resources containing information about opened files?

It's not an issue, it's just that the app was programmed to handle only one file per session.
What I am curious about is if you by accident did something like that, which would throw off the app's functions (like showing a different subtitle).

**Comment by Dacheisenberg** [comment]
I had the same problem. I’m not speech your language very well, so I'll try to explain.
When i work in a new Quilter file, the app work’s just fine, I can save the file in any folder that I choose, and i can continue writing in the same file. But, when I want to star a new .md file the app prompt’s that changes have been made to the file and ask if I want to close without saving. So each time I always clic on save and close, but the file apparently stay open, cause I can see the info from the file that it suppose to be close, but at the top of the window program, in the titlebar the name of the file is different, so I’m afraid to erase all my writing, and it is confusing.
I realized that when I say to the app “close without saving” the new .md file appears blank as it suppose to be. But when I do this, I always save first, and always copy my work, just to be sure that nothing will be lost, because I already loose three files too.
But to copy and verify each time you want to star a new file is annoying. Well, I hope I made myself understood. 
Thank you very much… and I have to say that these app it’s really great, I never find something to help me to be completely focus on my writing. Maybe a manual can help the users.
Thank again

Dach E.

**Comment by lainsce** [comment]
I see what you're saying and yes, it might be confusing to see that. I'll fix it, be assured though that the file is saved and that nothing is happening to your file, it's just that the subtitle is not being updated... :joy:

**Comment by Dacheisenberg** [comment]
Great Thanks a lot. I'll be looking foward for the update.

**Comment by bebeki** [comment]
I can confirm that the behavior Tomires described is happening for me in version 1.3.8. I've lost files regardless of if I open a document from the toolbar or click on one in the file manager. It doesn't seem to matter if the document was created in Quilter or using another app.

**Comment by lainsce** [comment]
I've found the culprit, it's the "New file" button, so I'm definitely fixing it for the 1.4.0 release.

**Comment by lainsce** [comment]
FIXED IT! Expect the fix in the 1.4.0 release, or if you're adventurous, compile it locally as per the README.

**Comment by Tomires** [comment]
Awesome, thanks for the quick fix!
