### ISSUE TITLE
[Feature request] Spellcheck databases from LibreOffice

### ISSUE THREAD

**Issue by Andrewsudarikov** [lainsce/quilter#92]
There is no issue with English language - spelling checker works perfectly.

But when you start using Cyrillic characters... The situation isn't as good as one would like it to be. Every single word is underlined, and I don't have time to add hundreds of words into the database.

I see 2 solutions to the problem: 
1. Create a subsystem to add LibreOffice spellchecking databases to Quilter. They cover almost all languages in active use and are pretty comprehensive. 
2. Make a switch in Preferences pane to turn off spell-checking. 

![quilter bug](https://user-images.githubusercontent.com/18544958/31756962-84d702e0-b4af-11e7-917a-8e123e457d48.png)

Thanks!

**Comment by lainsce** [comment]
Actually, Quilter will follow the system language for spellchecking, so if you’re on an English session, it will use the English spellchecking databases, and so on. Sadly, I can’t have more than one database being checked at a time, because that would need a lot of guessing work to match “Oh, now the user is using language X and Y, but not Z.” So I think this isn’t a bug. Also, you can disable spellchecking with a switch on Preferences.
